version: "3.8"
services:
  mongodb:
    image: 'mongo:4.4'
    volumes: 
      - data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: rob
      MONGO_INITDB_ROOT_PASSWORD: secret
    # env_file: -./env/mongo.env

  backend:
    # build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: 'goals-node' 
    ports:
      - '8080:80'
      # - '3000:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - /home/robert/Desktop/docker2/compose-01-starting-setup/compose-01-starting-setup/backend/env/backend.env
    depends_on:
      - mongodb

  frontend:
    image: 'goals-react'
    ports:
      - 3001:3000
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
